package com.fracta7.csgostats.presentation.user_stats

import com.fracta7.csgostats.domain.model.UserStats

data class UserStatsState(
    val stats: List<UserStats> = emptyList(),
    val totalMatches: Int = 0,
    val kills: Int = 0,
    val assists: Int = 0,
    val deaths: Int = 0,
    val hs: Float = 0f,
    val dpr: Float = 0f,
    val mvps: Int = 0,
    val startedAsCt: Int = 0,
    val duration: Int = 0,
    val totalKD: Float = 0f,
    val averageKD: Float = 0f,
    val averageKills: Float = 0f,
    val averageDeaths: Float = 0f,
    val averageAssists: Float = 0f,
    val averageMVPs: Float = 0f,
    val averageDuration: Float = 0f,
    val maxKills: Int = 0,
    val maxDeath: Int = 0,
    val maxAssists: Int = 0,
    val highestHS: Float = 0f,
    val maxMVPs: Int = 0,
    val maxDPR: Float = 0f,
    val maxDuration: Int = 0,
    val ctchance: Float = 0f,
    val hspercent: Float = 0f,
    val mvppercent: Float = 0f,
    val killpercent: Float = 0f,
    val assistpercent: Float = 0f,
    val deathpercent: Float = 0f,
    val durationpercent: Float = 0f,
    val totalkdchance: Float = 0f,
    val averagekdchance: Float = 0f,
    val dprchance: Float = 0f,
    val maxdprchance: Float = 0f,
)
